### ISSUE TITLE
Отсутствует README

### ISSUE THREAD

**Issue by pomponchik** [Weslia-Chartreux/public_fast#1]
Непонятно, о чем проект.

**Comment by Weslia-Chartreux** [comment]
Спасибо большое, что посмотрели код и выявили недостатки, я попытался все поправить и написал файл readme. Теперь вы можете ознакомиться с информацией о проекте.

**Comment by pomponchik** [comment]
Там до сих пор не сказано, о чем собственно проект.

**Comment by Weslia-Chartreux** [comment]
"Этот проект является частью проекта для работы с адресами и служит хранилищем адресов, которые пользователи уже вводили, чтобы не использовать все время api yandex и dadata." Вы считайте это недостаточным? Стоит добавить больше информации?

**Comment by pomponchik** [comment]
"Этот проект является частью проекта" - что? Какая-то рекурсия.

В целом да, описание по-прежнему ничего мне не говорит о том, зачем мне весь этот код мог бы быть нужен. Поставьте себя на место потенциального пользователя.

**Comment by pomponchik** [comment]
При этом там отсутствуют заголовки и форматирование по-прежнему далеко от идеала. Почитайте про возможности markdown.
